.TH KRV 1 krv\-0.1
.SH NAME
krv \- simple Krivine machine
.SH SYNOPSIS
.B krv
[dis|as|run]
.IR file
.SH DESCRIPTION
krv is a simple Krivine machine for Binary Lambda Calculus.
.SH OPTIONS
.TP
.BI run " file"
run the
.BI "file"
in the following format:
.TS
allbox;
c c.
00x	\\x
01xy	(x y)
1*n 0	n \- 1
.TE
.TP
.BI dis " file"
dissamble the
.BI "file"
in the same format as run and prints to stdout the corresponding in readable
format.
.TP
.BI as " file"
assemble the
.BI "file"
to binary lambda calculus to the format specified earlier. The input file has to
be in the following format:
.TS
allbox;
c c.
\\x	abstraction
(x y)	application
n	De Bruijn index
.TE
The \\ can be replaced by a unicode lambda and spaces don't count.
